window.AI_LANG_DATA = {
    ko: {
        "nav_about": "소개",
        "nav_experience": "경력",
        "nav_skills": "역량",
        "nav_contact": "문의",
        "hero_kicker": "AI 개발과 교육, 그리고 글로벌 비즈니스 파트너",
        "hero_h1_line1": "비즈니스에 힘이 되는 <span class='text-accent'>AI 앱 개발</span>, 바로 써먹는 <span class='text-neon-orange'>실전 IT 강의</span>",
        "hero_h1_line2": "",
        "hero_sub": "글로벌 프로젝트로 다져진 노하우로, 복잡한 기술을 알기 쉽게 풀어내고 업무에 바로 적용할 수 있는 솔루션을 만듭니다.",
        "cta_experience": "경력 보기",
        "cta_contact": "업무 협의",
        "profile_title": "실무형 <span class='text-accent'>AI 앱 개발자</span> & <span class='text-neon-orange'>IT 교육 전문가</span>",
        "profile_meta": "글로벌 현장에서 쌓은 마케팅·운영 노하우를 바탕으로, 비즈니스에 바로 쓰는 기술을 가르치고 만듭니다.",
        "about_h2": "핵심 프로필",
        "about_lead": "<ul class='space-y-4 text-lg text-muted/90'> <li class='flex gap-3 items-start'><i class='fa-solid fa-check text-accent mt-1.5 shrink-0'></i><span>글로벌 실무 감각을 갖춘 <strong>AI·IT 교육 전문가</strong></span></li> <li class='flex gap-3 items-start'><i class='fa-solid fa-check text-accent mt-1.5 shrink-0'></i><span>미국 및 싱가포르 포함 <strong>10년 이상의 글로벌 비즈니스 커리어</strong></span></li> <li class='flex gap-3 items-start'><i class='fa-solid fa-check text-accent mt-1.5 shrink-0'></i><span>두산로보틱스 · 레인보우로보틱스 제휴 <strong>주방용 로봇 개발 및 협업</strong> (싱가포르 적용)</span></li> <li class='flex gap-3 items-start'><i class='fa-solid fa-check text-accent mt-1.5 shrink-0'></i><span>SNS 채널 구축부터 콘텐츠 기획까지, <strong>통합 마케팅 솔루션 제공</strong></span></li> </ul>",
        "about_edu_h3": "학력",
        "about_edu_p": "전자계산학과 학사 · 영어영문학 학사",
        "about_teach_h3": "IT/AI 교육",
        "about_teach_p": "<ul class='space-y-2 mt-2'> <li class='flex gap-2 items-start'><i class='fa-solid fa-check text-accent text-sm mt-1.5 shrink-0'></i><span>누구나 이해할 수 있는 AI 활용 교육 기획</span></li> <li class='flex gap-2 items-start'><i class='fa-solid fa-check text-accent text-sm mt-1.5 shrink-0'></i><span>비전공자와 시니어도 이해할 수 있는 IT·AI 강의 진행</span></li> <li class='flex gap-2 items-start'><i class='fa-solid fa-check text-accent text-sm mt-1.5 shrink-0'></i><span>어려운 IT·AI 개념을 쉽게 풀어내는 교육 콘텐츠 설계</span></li> <li class='flex gap-2 items-start'><i class='fa-solid fa-check text-accent text-sm mt-1.5 shrink-0'></i><span>일상에 바로 쓰이는 IT·AI 활용 중심 강의</span></li> </ul>",
        "exp_h2": "주요 경력",
        "exp_lead": "디지털 마케팅 리더십부터 IT 교육, AI 응용까지 목표에 맞는 실행을 설계하고 결과를 만듭니다.",
        "exp1_t": "AI 기술 솔루션 & 크리에이티브 전문가",
        "exp1_d": "AI 응용 앱 개발 · 업무 자동화 시스템 구축 · 생성형 AI 영상/이미지 제작 · 웹사이트 구축",
        "exp2_t": "IT 교육 전문 강사",
        "exp2_d": "미국에서 10년간 현지인 대상 IT 활용 교육 기획·운영 (한국일보/조선일보 문화센터)",
        "exp3_t": "글로벌 기술·비즈니스 프로젝트 경험",
        "exp3_d": "AI·로보틱스 기반 사업 추진, 글로벌 마케팅 및 운영 관리, 실무형 기술 교육 진행",
        "exp4_t": "Business Manager — 1DERFOOD (Singapore)",
        "exp4_d": "푸드테크 프로젝트: 두산로보틱스·레인보우로보틱스 제휴 주방 로봇 개발 및 싱가포르 현지 적용",
        "exp5_t": "소셜미디어 전략연구소 실장 (General Manager)",
        "exp5_d": "브랜드 맞춤형 SNS 구축 및 통합 마케팅 설계 | 데이터 기반 트렌드 분석과 콘텐츠 기획",
        "exp6_t": "리무진 웨딩카 법인 대표 · 12개국 글로벌 성우 에이전시 운영",
        "exp6_d": "법인 운영 및 국내 외국어 성우 수요 기업 대상 해외 성우 섭외 및 매칭",
        "exp7_t": "VAN사 전산실 시스템 운영, 웹마스터",
        "exp7_d": "금융 인프라 데이터 처리 및 보안 시스템 운영, 홈페이지 제작 및 서버 관리",
        "exp8_t": "중소기업 총괄이사 (Executive Director)",
        "exp8_d": "해외 영업, 구매, 생산 관리 총괄 및 제품 기획부터 판매까지 전체 운영 프로세스 최적화",
        "skills_h2": "핵심 역량",
        "skills_lead": "실무형 AI 솔루션 도입과 맞춤형 교육, 기획 단계부터 실행까지 직접 챙깁니다.",
        "tag1": "Robotics & AI: 협동 로봇 솔루션 · 주방 자동화 기획",
        "tag2": "Digital Marketing: 소셜미디어 전략 · 브랜드 빌딩 · 퍼포먼스 분석",
        "tag3": "Global & Lang: 영어영문학 · 미국 10년 · 비즈니스 영어",
        "tag4": "IT & Dev: 전자계산학 · AI 솔루션 · 시스템 인프라 이해",
        "tag5": "AI & 콘텐츠: 업무 자동화 · AI 앱 · 디지털 콘텐츠 제작",
        "tag6": "Web & Design : 웹사이트 제작 · UI/UX 디자인 · 영상 콘텐츠",
        "contact_h2": "문의",
        "contact_lead": "프로젝트 협업 및 강연/교육 문의 내용을 남겨주시면 확인 후 연락처로 답변드리겠습니다.",
        "contact_email_label": "Email",
        "contact_btn": "메일 보내기",
        "contact_subject_label": "제목",
        "contact_name_label": "이름/회사명",
        "contact_phone_label": "연락처",
        "contact_message_label": "내용",
        "contact_submit_btn": "문의 사항 보내기",
        "footer_note": "© 2026 Mr.Sure. All Rights Reserved."
    },
    en: {
        "nav_about": "About",
        "nav_experience": "Experience",
        "nav_skills": "Skills",
        "nav_contact": "Contact",
        "hero_kicker": "AI Development & Education, Global Business Partner",
        "hero_h1_line1": "Business-Empowering <span class='text-accent'>AI App Development</span>,",
        "hero_h1_line2": "Execution-Ready <span class='text-neon-orange'>Practical IT Training</span>",
        "hero_sub": "With know-how forged in global projects, I simplify complex technologies and build solutions ready for immediate business application.",
        "cta_experience": "View Experience",
        "cta_contact": "Email Me",
        "profile_title": "Execution-Focused <span class='text-accent'>AI App Developer</span> & <span class='text-neon-orange'>IT Education Expert</span>",
        "profile_meta": "Leveraging global marketing and operations expertise to teach and build applied technologies for business.",
        "about_h2": "Profile Summary",
        "about_lead": "<ul class='space-y-4 text-lg text-muted/90'> <li class='flex gap-3 items-start'><i class='fa-solid fa-check text-accent mt-1.5 shrink-0'></i><span>AI/IT Education Expert with <strong>Global Practical Experience</strong></span></li> <li class='flex gap-3 items-start'><i class='fa-solid fa-check text-accent mt-1.5 shrink-0'></i><span><strong>10+ Years Global Business Career</strong> (incl. US & Singapore)</span></li> <li class='flex gap-3 items-start'><i class='fa-solid fa-check text-accent mt-1.5 shrink-0'></i><span>Kitchen Robot Development & Collaboration (Doosan/Rainbow Robotics, <strong>Applied in Singapore</strong>)</span></li> <li class='flex gap-3 items-start'><i class='fa-solid fa-check text-accent mt-1.5 shrink-0'></i><span>Integrated Marketing Solutions: From <strong>SNS Channel Building to Content Planning</strong></span></li> </ul>",
        "about_edu_h3": "Education",
        "about_edu_p": "B.A. in Computer Science · B.A. in English Literature",
        "about_teach_h3": "IT / AI Education",
        "about_teach_p": "<ul class='space-y-2 mt-2'> <li class='flex gap-2 items-start'><i class='fa-solid fa-check text-accent text-sm mt-1.5 shrink-0'></i><span>Planning AI utilization education for everyone</span></li> <li class='flex gap-2 items-start'><i class='fa-solid fa-check text-accent text-sm mt-1.5 shrink-0'></i><span>IT/AI lectures understandable by non-majors and seniors</span></li> <li class='flex gap-2 items-start'><i class='fa-solid fa-check text-accent text-sm mt-1.5 shrink-0'></i><span>Designing content that simplifies difficult concepts</span></li> <li class='flex gap-2 items-start'><i class='fa-solid fa-check text-accent text-sm mt-1.5 shrink-0'></i><span>Practical IT/AI training focused on daily use</span></li> </ul>",
        "exp_h2": "Professional Experience",
        "exp_lead": "From digital marketing leadership to IT education and applied AI, I build execution that aligns with goals and delivers outcomes.",
        "exp1_t": "AI Tech Solutions & Creative Specialist",
        "exp1_d": "AI App Development · Workflow Automation · Generative AI Video/Image Creation · Website Building",
        "exp2_t": "IT Instructor (10 years in the U.S.)",
        "exp2_d": "Planned and delivered IT and digital literacy education for Korean communities via Korea Times / Chosun Ilbo Culture Center.",
        "exp3_t": "Executive Director — SME",
        "exp3_d": "Oversaw overseas sales, purchasing, production; Optimized entire operation process from product planning to sales.",
        "exp4_t": "Business Manager — 1DERFOOD (Singapore)",
        "exp4_d": "Led a food-tech project partnering with Doosan Robotics and Rainbow Robotics to develop kitchen robots and deploy them in Singapore.",
        "exp5_t": "General Manager — Social Media Strategy Research Institute",
        "exp5_d": "Built brand-specific social channels and integrated marketing (IMC) strategies. Led big-data-driven social trend analysis and new media content strategy.",
        "exp6_t": "CEO — Limousine Wedding Car Corporation / Global Voice Agency Operator",
        "exp6_d": "Managed business operations and coordinated projects with external partners.",
        "exp7_t": "Systems Operations — VAN Company",
        "exp7_d": "Operated financial infrastructure systems, including data processing and security operations.",
        "exp8_t": "Convergence Projects — Global · Education · Technology",
        "exp8_d": "Led execution-focused projects integrating robotics/AI commercialization, strategic marketing, global operations, and convergence education.",
        "skills_h2": "Core Skills",
        "skills_lead": "Directly managing everything from practical AI solution implementation and tailored education to planning and execution.",
        "tag1": "Robotics & AI: Cobot solutions · Kitchen automation planning",
        "tag2": "Digital Marketing: Social strategy · Brand building · Performance analytics",
        "tag3": "Global & Language: English major · 10 years in the U.S. · Business English",
        "tag4": "IT & Dev: Computer Science · AI solutions · Systems & infrastructure understanding",
        "tag5": "AI & Content: Automation · AI apps · Digital content production",
        "tag6": "Web & Design: Website Creation · UI/UX Design · Video Content",
        "contact_h2": "Contact",
        "contact_lead": "Please leave a message about collaboration or speaking/training inquiries, and I will respond to your contact info.",
        "contact_email_label": "Email",
        "contact_email_label": "Email",
        "contact_btn": "Send Email",
        "contact_subject_label": "Subject",
        "contact_name_label": "Name / Company",
        "contact_phone_label": "Contact Info",
        "contact_message_label": "Message",
        "contact_submit_btn": "Send Inquiry",
        "footer_note": "© 2026 Mr.Sure. All Rights Reserved."
    }
};
